/*
	Insert or Update each of the [Course] look up default values.

	NOTES:

	1) This script uses a temporary table, insert or update the values in the temporary table to apply changes; removed values will
	not take affect (by design) as they may still be referenced by rows in the database.
*/
BEGIN TRANSACTION

CREATE TABLE #Course(
    [Reference] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Title] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Level] INT NOT NULL,
    [Sector] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) 

INSERT #Course VALUES ('ST0004', 'Actuarial technician', 4, 'Agriculture, environmental and animal care')
INSERT #Course VALUES ('ST0010', 'Aerospace engineer', 6, 'Business and administration')
INSERT #Course VALUES ('ST0013', 'Aerospace software engineer', 6, 'Business and administration')
INSERT #Course VALUES ('ST0014', 'Aviation maintenance mechanic', 2, 'Business and administration')
INSERT #Course VALUES ('ST0015', 'Survival equipment fitter', 3, 'Business and administration')
INSERT #Course VALUES ('ST0023', 'Control systems engineer (degree)', 6, 'Care services')
INSERT #Course VALUES ('ST0024', 'Electrical or electronic technical support engineer (degree)', 6, 'Care services')
INSERT #Course VALUES ('ST0025', 'Manufacturing engineer (degree)', 6, 'Care services')
INSERT #Course VALUES ('ST0027', 'Product design and development engineer (degree)', 6, 'Care services')
INSERT #Course VALUES ('ST0031', 'Automotive glazing technician', 3, 'Care services')
INSERT #Course VALUES ('ST0108', 'Dental technician (integrated)', 5, 'Creative and design')
INSERT #Course VALUES ('ST0109', 'Dental practice manager', 4, 'Creative and design')
INSERT #Course VALUES ('ST0113', 'Dental nurse (integrated)', 3, 'Creative and design')
INSERT #Course VALUES ('ST0115', 'IT technical salesperson', 3, 'Digital')
INSERT #Course VALUES ('ST0116', 'Software developer', 4, 'Digital')
INSERT #Course VALUES ('ST0117', 'Business analyst', 4, 'Digital')
INSERT #Course VALUES ('ST0118', 'Data analyst', 4, 'Digital')
INSERT #Course VALUES ('ST0119', 'Digital and technology solutions professional', 6, 'Digital')
INSERT #Course VALUES ('ST0120', 'Digital support technician', 3, 'Digital')
INSERT #Course VALUES ('ST0127', 'Network engineer', 4, 'Digital')
INSERT #Course VALUES ('ST0128', 'Software development technician', 3, 'Digital')
INSERT #Course VALUES ('ST0129', 'Software tester', 4, 'Digital')
INSERT #Course VALUES ('ST0154', 'Maintenance and operations engineering technician', 3, 'Education and early years')
INSERT #Course VALUES ('ST0155', 'Gas engineering operative', 3, 'Education and early years')
INSERT #Course VALUES ('ST0156', 'Power network craftsperson', 3, 'Education and early years')
INSERT #Course VALUES ('ST0157', 'Electrical power protection and plant commissioning engineer', 4, 'Education and early years')
INSERT #Course VALUES ('ST0158', 'Dual fuel smart meter installer', 2, 'Education and early years')
INSERT #Course VALUES ('ST0159', 'Utilities engineering technician', 3, 'Education and early years')
INSERT #Course VALUES ('ST0171', 'Property maintenance operative', 2, 'Legal, finance and accounting')
INSERT #Course VALUES ('ST0175', 'Advanced credit controller and debt collection specialist', 3, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0176', 'Credit controller and collector', 2, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0177', 'Financial services administrator', 3, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0178', 'Financial services customer adviser', 2, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0179', 'Investment operations administrator', 2, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0180', 'Investment operations specialist', 4, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0181', 'Investment operations technician', 3, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0182', 'Mortgage adviser', 3, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0183', 'Paraplanner', 4, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0185', 'Senior financial services customer adviser', 3, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0187', 'Pensions administrator', 3, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0194', 'Fishmonger', 2, 'Construction and the built environment')
INSERT #Course VALUES ('ST0195', 'Food and drink maintenance engineer', 3, 'Construction and the built environment')
INSERT #Course VALUES ('ST0196', 'Food and drink technical operator', 3, 'Construction and the built environment')
INSERT #Course VALUES ('ST0198', 'Food industry technologist', 3, 'Construction and the built environment')
INSERT #Course VALUES ('ST0199', 'Food and drink process operator', 2, 'Construction and the built environment')
INSERT #Course VALUES ('ST0204', 'Gas network operative', 2, 'Education and early years')
INSERT #Course VALUES ('ST0205', 'Gas network craftsperson', 3, 'Education and early years')
INSERT #Course VALUES ('ST0209', 'Golf greenkeeper', 2, 'Hair and beauty')
INSERT #Course VALUES ('ST0241', 'Insurance professional', 4, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0248', 'Laboratory technician', 3, 'Catering and hospitality')
INSERT #Course VALUES ('ST0249', 'Science industry maintenance technician', 3, 'Catering and hospitality')
INSERT #Course VALUES ('ST0250', 'Science manufacturing technician', 3, 'Catering and hospitality')
INSERT #Course VALUES ('ST0266', 'Digital engineering technician', 3, 'Digital')
INSERT #Course VALUES ('ST0274', 'Seafarer (deck rating)', 2, 'Sales, marketing and procurement')
INSERT #Course VALUES ('ST0286', 'Senior journalist', 7, 'Health and science')
INSERT #Course VALUES ('ST0289', 'Nuclear scientist and nuclear engineer (integrated degree)', 6, 'Transport and logistics')
INSERT #Course VALUES ('ST0290', 'Nuclear health physics monitor', 2, 'Transport and logistics')
INSERT #Course VALUES ('ST0291', 'Nuclear operative', 2, 'Transport and logistics')
INSERT #Course VALUES ('ST0292', 'Nuclear welding inspection technician', 4, 'Transport and logistics')
INSERT #Course VALUES ('ST0315', 'Railway engineering design technician', 3, 'Protective services')
INSERT #Course VALUES ('ST0329', 'Junior estate agent', 2, 'Legal, finance and accounting')
INSERT #Course VALUES ('ST0345', 'Digital community manager', 4, 'Digital')
INSERT #Course VALUES ('ST0362', 'Compliance and risk officer', 3, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0363', 'Senior compliance and risk specialist', 6, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0374', 'Financial adviser', 4, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0380', 'Nuclear technician', 5, 'Transport and logistics')
INSERT #Course VALUES ('ST0393', 'Dairy technologist', 5, 'Construction and the built environment')
INSERT #Course VALUES ('ST0400', 'Small commercial vessel crewmember', 3, 'Sales, marketing and procurement')
INSERT #Course VALUES ('ST0409', 'Cyber security technical professional (integrated degree)', 6, 'Digital')
INSERT #Course VALUES ('ST0425', 'Broadcast and media systems technician', 5, 'Health and science')
INSERT #Course VALUES ('ST0428', 'Port marine operations officer', 4, 'Sales, marketing and procurement')
INSERT #Course VALUES ('ST0470', 'Digital user experience (UX) professional (integrated degree)', 6, 'Digital')
INSERT #Course VALUES ('ST0472', 'Financial services professional', 6, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0474', 'Motor finance specialist', 3, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0481', 'Digital marketer (integrated degree)', 6, 'Digital')
INSERT #Course VALUES ('ST0482', 'Digital and technology solutions specialist (integrated degree)', 7, 'Digital')
INSERT #Course VALUES ('ST0485', 'Network cable installer', 3, 'Digital')
INSERT #Course VALUES ('ST0499', 'Autocare technician', 2, 'Care services')
INSERT #Course VALUES ('ST0502', 'Actuary', 7, 'Agriculture, environmental and animal care')
INSERT #Course VALUES ('ST0505', 'IT solutions technician', 3, 'Digital')
INSERT #Course VALUES ('ST0538', 'Florist', 2, 'Hair and beauty')
INSERT #Course VALUES ('ST0543', 'Clinical dental technician (integrated)', 5, 'Creative and design')
INSERT #Course VALUES ('ST0561', 'Senior investment and commercial banking professional', 7, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0580', 'Brewer', 4, 'Construction and the built environment')
INSERT #Course VALUES ('ST0585', 'Data scientist (integrated degree)', 6, 'Digital')
INSERT #Course VALUES ('ST0589', 'Production chef', 2, 'Construction and the built environment')
INSERT #Course VALUES ('ST0592', 'Marina and boatyard operative', 2, 'Sales, marketing and procurement')
INSERT #Course VALUES ('ST0603', 'Professional economist (integrated degree)', 6, 'Agriculture, environmental and animal care')
INSERT #Course VALUES ('ST0621', 'Boatmaster', 3, 'Sales, marketing and procurement')
INSERT #Course VALUES ('ST0626', 'Laboratory scientist (degree)', 6, 'Catering and hospitality')
INSERT #Course VALUES ('ST0682', 'Digital device repair technician', 3, 'Digital')
INSERT #Course VALUES ('ST0701', 'Orthodontic therapist (integrated)', 4, 'Creative and design')
INSERT #Course VALUES ('ST0757', 'Radio network technician', 3, 'Digital')
INSERT #Course VALUES ('ST0763', 'Artificial intelligence (AI) data specialist', 7, 'Digital')
INSERT #Course VALUES ('ST0765', 'Harbour master', 6, 'Sales, marketing and procurement')
INSERT #Course VALUES ('ST0766', 'Debt adviser', 3, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0767', 'Water environment worker', 3, 'Catering and hospitality')
INSERT #Course VALUES ('ST0784', 'Nuclear reactor desk engineer', 6, 'Transport and logistics')
INSERT #Course VALUES ('ST0795', 'Data technician', 3, 'Digital')
INSERT #Course VALUES ('ST0796', 'Senior professional economist (integrated degree)', 7, 'Engineering and manufacturing')
INSERT #Course VALUES ('ST0825', 'DevOps engineer', 4, 'Digital')
INSERT #Course VALUES ('ST0842', 'Officer of the watch (near coastal)', 3, 'Sales, marketing and procurement')
INSERT #Course VALUES ('ST0855', 'Space engineering technician', 4, 'Business and administration')
INSERT #Course VALUES ('ST0863', 'Digital accessibility specialist', 4, 'Digital')
INSERT #Course VALUES ('ST0865', 'Cyber security technician', 3, 'Digital')
INSERT #Course VALUES ('ST0876', 'Water process operative', 2, 'Education and early years')
INSERT #Course VALUES ('ST0922', 'Professional arboriculturist', 6, 'Hair and beauty')
INSERT #Course VALUES ('ST0924', 'Horticulture and landscaping technical manager', 5, 'Hair and beauty')
INSERT #Course VALUES ('ST0949', 'Applications support lead', 4, 'Digital')
INSERT #Course VALUES ('ST0953', 'Game programmer', 7, 'Digital')
INSERT #Course VALUES ('ST0957', 'Spatial data specialist', 7, 'Digital')
INSERT #Course VALUES ('ST0964', 'Digital product manager', 4, 'Digital')
INSERT #Course VALUES ('ST0973', 'Information communications technician', 3, 'Digital')
INSERT #Course VALUES ('ST0974', 'Digital learning designer', 5, 'Digital')
INSERT #Course VALUES ('ST1020', 'Low carbon heating technician', 3, 'Education and early years')
INSERT #Course VALUES ('ST1021', 'Cyber security technologist (2021)', 4, 'Digital')
INSERT #Course VALUES ('ST1291', 'Water industry treatment process technician', 3, 'Education and early years')
INSERT #Course VALUES ('ST1292', 'Water industry network technician', 3, 'Education and early years')
INSERT #Course VALUES ('ST1324', 'Journalist', 5, 'Health and science')
INSERT #Course VALUES ('ST1343', 'Digital forensic technician', 4, 'Digital')
INSERT #Course VALUES ('ST1386', 'Data engineer', 5, 'Digital')

MERGE [Course] [Target] USING #Course [Source]
ON ([Source].[Reference] = [Target].[Reference])
WHEN MATCHED
    THEN UPDATE SET 
        [Target].[Title] = [Source].[Title],
        [Target].[Level] = [Source].[Level],
        [Target].[Sector] = [Source].[Sector]

WHEN NOT MATCHED BY TARGET 
    THEN INSERT ([Reference], [Title], [Level], [Sector] )
         VALUES ([Source].[Reference], [Source].[Title], [Source].[Level], [Source].[Sector]);

COMMIT TRANSACTION
