/*
	Insert or Update each of the [Standard] look up default values.

	NOTES:

	1) This script uses a temporary table, insert or update the values in the temporary table to apply changes; removed values will
	not take affect (by design) as they may still be referenced by rows in the database.
*/

BEGIN TRANSACTION

DROP TABLE IF EXISTS #Standard

CREATE TABLE #Standard(
    [StandardReference] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [StandardTitle] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [StandardLevel] INT NOT NULL,
    [StandardSector] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) 

INSERT #Standard VALUES ('ST0001', 'Accountancy or taxation professional', 7, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0002', 'Assistant accountant', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0003', 'Professional accounting or taxation technician', 4, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0004', 'Actuarial technician', 4, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0005', 'Adult care worker', 2, 'Care services')
INSERT #Standard VALUES ('ST0006', 'Lead adult care worker', 3, 'Care services')
INSERT #Standard VALUES ('ST0007', 'Lead practitioner in adult care', 4, 'Care services')
INSERT #Standard VALUES ('ST0008', 'Leader in adult care', 5, 'Care services')
INSERT #Standard VALUES ('ST0010', 'Aerospace engineer', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0013', 'Aerospace software engineer', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0014', 'Aviation maintenance mechanic', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0015', 'Survival equipment fitter', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0018', 'Crop technician', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0019', 'Aircraft certifying technician', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0023', 'Control systems engineer (degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0024', 'Electrical or electronic technical support engineer (degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0025', 'Manufacturing engineer (degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0027', 'Product design and development engineer (degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0031', 'Automotive glazing technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0033', 'Motor vehicle service and maintenance technician - light vehicle', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0037', 'Aviation ground operative', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0038', 'Aviation ground specialist', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0039', 'Aviation operations manager', 4, 'Transport and logistics')
INSERT #Standard VALUES ('ST0040', 'Building services engineering site management (degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0041', 'Building services engineering senior technician', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0042', 'Civil engineering site management (degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0043', 'Construction design and build technician', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0044', 'Design and construction management (degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0045', 'Construction quantity surveyor (degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0046', 'Civil engineering senior technician', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0047', 'Construction site management (degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0048', 'Construction site supervisor', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0049', 'Construction quantity surveying technician', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0051', 'Highway electrical maintenance and installation operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0052', 'Highways electrician or service operative', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0053', 'Highways maintenance skilled operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0055', 'Bespoke cutter and tailor', 5, 'Creative and design')
INSERT #Standard VALUES ('ST0056', 'Bid and proposal co-ordinator', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0058', 'Animal technologist', 3, 'Health and science')
INSERT #Standard VALUES ('ST0059', 'Boatbuilder', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0061', 'Building services engineering service and maintenance engineer', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0062', 'Building services engineering craftsperson', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0063', 'Building services engineering technician 2022', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0065', 'Building services engineering installer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0067', 'Bus and coach engineering technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0068', 'Heavy vehicle service and maintenance technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0070', 'Business administrator', 3, 'Business and administration')
INSERT #Standard VALUES ('ST0071', 'Customer service specialist', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0072', 'Customer service practitioner', 2, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0073', 'Payroll administrator', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0077', 'Advanced butcher', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0078', 'Butcher', 2, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0087', 'Children, young people and families manager', 5, 'Care services')
INSERT #Standard VALUES ('ST0088', 'Children, young people and families practitioner', 4, 'Care services')
INSERT #Standard VALUES ('ST0091', 'Civil engineering technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0092', 'Community energy specialist', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0093', 'Community sport and health officer', 3, 'Health and science')
INSERT #Standard VALUES ('ST0094', 'Composites technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0095', 'Bricklayer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0096', 'Plasterer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0100', 'Conveyancing technician', 4, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0101', 'Licensed conveyancer', 6, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0102', 'Probate technician', 4, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0103', 'Express delivery operative', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0105', 'Content creator', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0107', 'Systems engineer (degree)', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0108', 'Dental technician (integrated)', 5, 'Health and science')
INSERT #Standard VALUES ('ST0109', 'Dental practice manager', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0113', 'Dental nurse (integrated)', 3, 'Health and science')
INSERT #Standard VALUES ('ST0115', 'IT technical salesperson', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0116', 'Software developer', 4, 'Digital')
INSERT #Standard VALUES ('ST0117', 'Business analyst', 4, 'Digital')
INSERT #Standard VALUES ('ST0118', 'Data analyst', 4, 'Digital')
INSERT #Standard VALUES ('ST0119', 'Digital and technology solutions professional', 6, 'Digital')
INSERT #Standard VALUES ('ST0120', 'Digital support technician', 3, 'Digital')
INSERT #Standard VALUES ('ST0127', 'Network engineer', 4, 'Digital')
INSERT #Standard VALUES ('ST0128', 'Software development technician', 3, 'Digital')
INSERT #Standard VALUES ('ST0129', 'Software tester', 4, 'Digital')
INSERT #Standard VALUES ('ST0135', 'Early years educator', 3, 'Education and early years')
INSERT #Standard VALUES ('ST0144', 'Material processing plant operator', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0149', 'Learning and skills teacher', 5, 'Education and early years')
INSERT #Standard VALUES ('ST0150', 'Electrical, electronic product service and installation engineer', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0151', 'Embedded electronic systems design and development engineer (degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0152', 'Installation and maintenance electrician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0154', 'Maintenance and operations engineering technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0155', 'Gas engineering operative', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0156', 'Power network craftsperson', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0157', 'Electrical power protection and plant commissioning engineer', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0158', 'Dual fuel smart meter installer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0159', 'Utilities engineering technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0161', 'Junior energy manager', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0162', 'Engineering construction pipefitter', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0163', 'Project controls technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0164', 'Engineering design and draughtsperson', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0166', 'Equine groom', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0167', 'Senior equine groom', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0168', 'Event assistant', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0170', 'Facilities management supervisor', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0171', 'Property maintenance operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0172', 'Farrier', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0173', 'Fashion studio assistant', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0174', 'Props technician', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0175', 'Advanced credit controller and debt collection specialist', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0176', 'Credit controller and collector', 2, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0177', 'Financial services administrator', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0178', 'Financial services customer adviser', 2, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0179', 'Investment operations administrator', 2, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0180', 'Investment operations specialist', 4, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0181', 'Investment operations technician', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0182', 'Mortgage adviser', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0183', 'Paraplanner', 4, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0185', 'Senior financial services customer adviser', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0187', 'Pensions administrator', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0188', 'Fire safety advisor', 3, 'Protective services')
INSERT #Standard VALUES ('ST0189', 'Fire emergency and security systems technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0191', 'Baker', 2, 'Catering and hospitality')
INSERT #Standard VALUES ('ST0192', 'Improvement practitioner', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0193', 'Improvement technician', 3, 'Business and administration')
INSERT #Standard VALUES ('ST0194', 'Fishmonger', 2, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0195', 'Food and drink maintenance engineer', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0196', 'Food and drink technical operator', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0197', 'Food industry technical professional (integrated degree)', 6, 'Health and science')
INSERT #Standard VALUES ('ST0198', 'Food industry technologist', 3, 'Health and science')
INSERT #Standard VALUES ('ST0199', 'Food and drink process operator', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0201', 'Supply chain practitioner (fast moving consumer good) (previously Operator Manager)', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0202', 'Footwear manufacturer', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0203', 'Furniture manufacturer', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0204', 'Gas network operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0205', 'Gas network craftsperson', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0208', 'Golf course manager', 5, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0209', 'Golf greenkeeper', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0210', 'Sports turf operative', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0211', 'Advanced beauty therapist', 3, 'Hair and beauty')
INSERT #Standard VALUES ('ST0213', 'Hairdressing professional', 2, 'Hair and beauty')
INSERT #Standard VALUES ('ST0214', 'Advanced and creative hair professional', 3, 'Hair and beauty')
INSERT #Standard VALUES ('ST0215', 'Assistant practitioner (health)', 5, 'Health and science')
INSERT #Standard VALUES ('ST0216', 'Healthcare support worker', 2, 'Health and science')
INSERT #Standard VALUES ('ST0217', 'Senior healthcare support worker', 3, 'Health and science')
INSERT #Standard VALUES ('ST0218', 'Healthcare science assistant', 2, 'Health and science')
INSERT #Standard VALUES ('ST0220', 'Healthcare science associate', 4, 'Health and science')
INSERT #Standard VALUES ('ST0221', 'Archaeological technician', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0222', 'HM forces serviceperson (protective services)', 2, 'Protective services')
INSERT #Standard VALUES ('ST0223', 'Arborist', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0225', 'Horticulture or landscape construction operative', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0226', 'Horticulture or landscaping supervisor', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0227', 'Chef de partie', 3, 'Catering and hospitality')
INSERT #Standard VALUES ('ST0228', 'Commis chef', 2, 'Catering and hospitality')
INSERT #Standard VALUES ('ST0229', 'Hospitality manager', 4, 'Catering and hospitality')
INSERT #Standard VALUES ('ST0230', 'Hospitality supervisor', 3, 'Catering and hospitality')
INSERT #Standard VALUES ('ST0232', 'Senior production chef', 3, 'Catering and hospitality')
INSERT #Standard VALUES ('ST0233', 'Hospitality team member', 2, 'Catering and hospitality')
INSERT #Standard VALUES ('ST0234', 'Housing and property management', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0235', 'Housing and property management assistant', 2, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0236', 'Senior housing and property management', 4, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0238', 'People professional', 5, 'Business and administration')
INSERT #Standard VALUES ('ST0239', 'HR support', 3, 'Business and administration')
INSERT #Standard VALUES ('ST0240', 'Insurance practitioner', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0241', 'Insurance professional', 4, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0242', 'Land-based service engineer', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0243', 'Land-based service engineering technician', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0244', 'Chartered legal executive', 6, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0245', 'Paralegal', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0246', 'Solicitor', 7, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0248', 'Laboratory technician', 3, 'Health and science')
INSERT #Standard VALUES ('ST0249', 'Science industry maintenance technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0250', 'Science manufacturing technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0251', 'Stairlift, platform lift, service lift electromechanic', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0252', 'Lift and escalator electromechanic', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0257', 'Large goods vehicle (LGV) driver C + E', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0258', 'Supply chain operator', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0259', 'Supply chain warehouse operative', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0263', 'Craft carpentry and joinery', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0264', 'Carpentry and joinery', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0265', 'Construction assembly and installation operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0266', 'Digital engineering technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0267', 'Lifting technician', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0268', 'Piling attendant', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0269', 'Hire controller (plant, tools and equipment)', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0270', 'Roofer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0271', 'Steel fixer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0272', 'Chartered manager (degree)', 6, 'Business and administration')
INSERT #Standard VALUES ('ST0273', 'Junior management consultant', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0274', 'Seafarer (deck rating)', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0276', 'Maritime mechanical and electrical mechanic', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0282', 'Metrology technician', 3, 'Health and science')
INSERT #Standard VALUES ('ST0283', 'Senior metrology technician', 5, 'Health and science')
INSERT #Standard VALUES ('ST0286', 'Senior journalist', 7, 'Creative and design')
INSERT #Standard VALUES ('ST0287', 'Associate ambulance practitioner', 4, 'Health and science')
INSERT #Standard VALUES ('ST0288', 'Non-destructive testing engineering technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0289', 'Nuclear scientist and nuclear engineer (integrated degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0290', 'Nuclear health physics monitor', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0291', 'Nuclear operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0292', 'Nuclear welding inspection technician', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0295', 'Painter and decorator', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0299', 'Pharmacy services assistant', 2, 'Health and science')
INSERT #Standard VALUES ('ST0300', 'Pharmacy technician (integrated)', 3, 'Health and science')
INSERT #Standard VALUES ('ST0301', 'Leisure duty manager', 3, 'Business and administration')
INSERT #Standard VALUES ('ST0302', 'Personal trainer', 3, 'Health and science')
INSERT #Standard VALUES ('ST0303', 'Plumbing and domestic heating technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0304', 'Police constable (integrated degree)', 6, 'Protective services')
INSERT #Standard VALUES ('ST0307', 'Port operative', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0309', 'Print technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0310', 'Associate project manager', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0311', 'Public relations and communications assistant', 4, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0313', 'Commercial procurement and supply (formerly Public sector commercial professional)', 4, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0314', 'Public service operational delivery officer', 3, 'Business and administration')
INSERT #Standard VALUES ('ST0315', 'Railway engineering design technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0316', 'Rail engineering advanced technician', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0317', 'Rail engineering operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0318', 'Rail engineering technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0320', 'Recruitment consultant', 3, 'Business and administration')
INSERT #Standard VALUES ('ST0321', 'Recruitment resourcer', 2, 'Business and administration')
INSERT #Standard VALUES ('ST0322', 'Refrigeration air conditioning and heat pump engineering technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0325', 'Retail manager', 4, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0326', 'Retail team leader', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0327', 'Retailer', 2, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0328', 'Bespoke saddler', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0329', 'Junior estate agent', 2, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0330', 'Security first line manager', 3, 'Protective services')
INSERT #Standard VALUES ('ST0331', 'Chartered surveyor (degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0332', 'Surveying technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0333', 'Commercial thermal insulation operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0334', 'Trade supplier', 2, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0336', 'Transport planning technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0337', 'Passenger transport operations manager', 4, 'Transport and logistics')
INSERT #Standard VALUES ('ST0338', 'Passenger transport driver - bus and coach or tram', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0339', 'Passenger transport operative', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0340', 'Travel consultant', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0341', 'Production assistant - screen and audio', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0342', 'Outside broadcasting engineer (integrated degree)', 7, 'Creative and design')
INSERT #Standard VALUES ('ST0343', 'Veterinary nurse', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0345', 'Digital community manager', 4, 'Digital')
INSERT #Standard VALUES ('ST0349', 'Welder', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0352', 'Accident repair technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0358', 'Non-destructive testing (NDT) operator', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0359', 'Scaffolder', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0362', 'Compliance and risk officer', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0363', 'Senior compliance and risk specialist', 6, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0364', 'Marine engineer', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0366', 'Fencing installer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0368', 'Wall and floor tiler', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0369', 'Non-destructive testing engineer (degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0372', 'Building services design engineer (degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0373', 'Powered pedestrian door installer and service engineer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0374', 'Financial adviser', 4, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0375', 'Tunnelling operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0376', 'Motorcycle technician (repair and maintenance)', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0378', 'Blacksmith', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0380', 'Nuclear technician', 5, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0382', 'Organ builder', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0383', 'Spectacle technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0384', 'Team leader or supervisor', 3, 'Business and administration')
INSERT #Standard VALUES ('ST0385', 'Operations or departmental manager', 5, 'Business and administration')
INSERT #Standard VALUES ('ST0386', 'Custody and detention professional', 3, 'Protective services')
INSERT #Standard VALUES ('ST0387', 'Lift truck and powered access engineering technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0388', 'Interior systems installer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0389', 'Poultry worker', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0390', 'Leisure team member', 2, 'Health and science')
INSERT #Standard VALUES ('ST0393', 'Dairy technologist', 5, 'Health and science')
INSERT #Standard VALUES ('ST0395', 'Watchmaker', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0396', 'Cultural learning and participation officer', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0397', 'Animal care and welfare assistant', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0398', 'Animal trainer', 4, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0400', 'Small commercial vessel crewmember', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0403', 'Vehicle damage panel technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0405', 'Vehicle damage mechanical, electrical and trim (MET) technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0406', 'Vehicle damage assessor', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0407', 'Process automation engineer (degree)', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0408', 'Countryside worker', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0409', 'Cyber security technical professional (integrated degree)', 6, 'Digital')
INSERT #Standard VALUES ('ST0410', 'Senior and head of facilities management (integrated degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0411', 'Project manager (integrated degree)', 6, 'Business and administration')
INSERT #Standard VALUES ('ST0412', 'Underkeeper', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0413', 'Healthcare science practitioner (integrated degree)', 6, 'Health and science')
INSERT #Standard VALUES ('ST0414', 'Military engineering construction technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0417', 'Civil engineer (degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0418', 'Abattoir worker', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0420', 'Lean manufacturing operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0422', 'Science manufacturing process operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0423', 'Business to business sales professional (integrated degree)', 6, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0424', 'Broadcast and media systems technical operator', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0425', 'Broadcast and media systems technician', 5, 'Creative and design')
INSERT #Standard VALUES ('ST0426', 'Broadcast and media systems engineer (integrated degree)', 6, 'Creative and design')
INSERT #Standard VALUES ('ST0427', 'Marine pilot', 5, 'Transport and logistics')
INSERT #Standard VALUES ('ST0428', 'Port marine operations officer', 4, 'Transport and logistics')
INSERT #Standard VALUES ('ST0430', 'Regulatory compliance officer', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0431', 'Rehabilitation worker (visual impairment)', 5, 'Health and science')
INSERT #Standard VALUES ('ST0432', 'Engineering fitter', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0433', 'Engineering construction erector rigger', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0439', 'Jewellery, silversmithing, and allied trades professional', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0442', 'Stonemason', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0447', 'Clock maker', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0448', 'Vehicle damage paint technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0453', 'Water treatment technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0454', 'Teaching assistant', 3, 'Education and early years')
INSERT #Standard VALUES ('ST0456', 'Post graduate engineer', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0457', 'Engineering technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0458', 'Textile manufacturing operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0460', 'Leather craftsperson', 2, 'Creative and design')
INSERT #Standard VALUES ('ST0461', 'Formworker', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0463', 'Industrial coatings applicator', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0464', 'Smart home technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0465', 'Risk and safety management professional (degree)', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0467', 'Poultry technician', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0469', 'Bookbinder', 2, 'Creative and design')
INSERT #Standard VALUES ('ST0470', 'Digital user experience (UX) professional (integrated degree)', 6, 'Digital')
INSERT #Standard VALUES ('ST0471', 'Express delivery manager (degree)', 6, 'Transport and logistics')
INSERT #Standard VALUES ('ST0472', 'Financial services professional', 6, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0473', 'Science industry process and plant engineer (degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0474', 'Motor finance specialist', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0475', 'Electrical power networks engineer', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0476', 'Assistant puppet maker', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0477', 'Academic professional', 7, 'Education and early years')
INSERT #Standard VALUES ('ST0478', 'Community activator coach', 2, 'Health and science')
INSERT #Standard VALUES ('ST0479', 'Outdoor activity instructor', 3, 'Health and science')
INSERT #Standard VALUES ('ST0480', 'Senior leader', 7, 'Business and administration')
INSERT #Standard VALUES ('ST0481', 'Digital marketer (integrated degree)', 6, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0482', 'Digital and technology solutions specialist (integrated degree)', 7, 'Digital')
INSERT #Standard VALUES ('ST0483', 'Emergency contact handler', 3, 'Protective services')
INSERT #Standard VALUES ('ST0484', 'Facilities manager', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0485', 'Network cable installer', 3, 'Digital')
INSERT #Standard VALUES ('ST0486', 'Operational firefighter', 3, 'Protective services')
INSERT #Standard VALUES ('ST0487', 'Specialist rescue operative', 4, 'Protective services')
INSERT #Standard VALUES ('ST0488', 'Junior animator', 4, 'Creative and design')
INSERT #Standard VALUES ('ST0489', 'Storyboard artist', 7, 'Creative and design')
INSERT #Standard VALUES ('ST0490', 'Teacher', 6, 'Education and early years')
INSERT #Standard VALUES ('ST0491', 'Geospatial survey technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0492', 'Geospatial mapping and science specialist (degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0493', 'Podiatrist', 6, 'Health and science')
INSERT #Standard VALUES ('ST0494', 'Probation services practitioner', 3, 'Protective services')
INSERT #Standard VALUES ('ST0495', 'Rail and rail systems engineer', 5, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0496', 'Rail and rail systems senior engineer (integrated degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0497', 'Rail and rail systems principal engineer (integrated degree)', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0499', 'Autocare technician', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0502', 'Actuary', 7, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0504', 'Floorlayer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0505', 'IT solutions technician', 3, 'Digital')
INSERT #Standard VALUES ('ST0507', 'Metal recycling general operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0509', 'Police community support officer', 4, 'Protective services')
INSERT #Standard VALUES ('ST0510', 'Social worker (integrated degree)', 6, 'Care services')
INSERT #Standard VALUES ('ST0511', 'Mineral and construction product sampling and testing operations', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0512', 'Serious and complex crime investigator (integrated degree)', 6, 'Protective services')
INSERT #Standard VALUES ('ST0513', 'Groundworker', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0515', 'Manufacturing manager (integrated degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0516', 'Intelligence analyst', 4, 'Protective services')
INSERT #Standard VALUES ('ST0517', 'Occupational therapist', 6, 'Health and science')
INSERT #Standard VALUES ('ST0518', 'Physician associate - integrated degree', 7, 'Health and science')
INSERT #Standard VALUES ('ST0519', 'Physiotherapist', 6, 'Health and science')
INSERT #Standard VALUES ('ST0520', 'Senior insurance professional', 6, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0521', 'Industrial thermal insulation technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0522', 'Youth worker', 6, 'Care services')
INSERT #Standard VALUES ('ST0523', 'First officer pilot', 6, 'Transport and logistics')
INSERT #Standard VALUES ('ST0524', 'Sporting excellence professional', 3, 'Health and science')
INSERT #Standard VALUES ('ST0525', 'Creative industries production manager', 7, 'Creative and design')
INSERT #Standard VALUES ('ST0526', 'Policy officer', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0527', 'Church minister (integrated degree)', 6, 'Care services')
INSERT #Standard VALUES ('ST0528', 'High speed rail and infrastructure technician', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0529', 'Food and drink advanced engineer (integrated degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0531', 'Wood product manufacturing operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0532', 'Publishing assistant', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0533', 'Architect (integrated degree)', 7, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0534', 'Architectural assistant (integrated degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0535', 'Clinical coder', 3, 'Health and science')
INSERT #Standard VALUES ('ST0536', 'Chartered town planner (degree)', 7, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0537', 'Engineering operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0538', 'Florist', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0539', 'International freight forwarding specialist', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0540', 'Fashion and textiles product technologist', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0541', 'Fashion and textiles pattern cutter', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0542', 'Oral health practitioner', 4, 'Health and science')
INSERT #Standard VALUES ('ST0543', 'Clinical dental technician (integrated)', 5, 'Health and science')
INSERT #Standard VALUES ('ST0544', 'Port agent', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0545', 'Waste resource operative', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0547', 'Retail leadership (integrated degree)', 6, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0548', 'Supply chain leadership professional (integrated degree)', 6, 'Transport and logistics')
INSERT #Standard VALUES ('ST0549', 'Sewing machinist', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0550', 'Safety, health and environment technician', 3, 'Protective services')
INSERT #Standard VALUES ('ST0551', 'Early years lead practitioner', 5, 'Education and early years')
INSERT #Standard VALUES ('ST0554', 'Sonographer (integrated degree)', 6, 'Health and science')
INSERT #Standard VALUES ('ST0555', 'Improvement specialist', 5, 'Business and administration')
INSERT #Standard VALUES ('ST0556', 'Improvement leader', 6, 'Business and administration')
INSERT #Standard VALUES ('ST0558', 'Cabin crew', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0559', 'Museums and galleries technician', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0561', 'Senior investment and commercial banking professional', 7, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0562', 'Learning and development practitioner', 3, 'Business and administration')
INSERT #Standard VALUES ('ST0563', 'Learning and development consultant business partner', 5, 'Business and administration')
INSERT #Standard VALUES ('ST0564', 'Advanced clinical practitioner (integrated degree)', 7, 'Health and science')
INSERT #Standard VALUES ('ST0566', 'Metal casting, foundry and patternmaking technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0567', 'Paramedic', 6, 'Health and science')
INSERT #Standard VALUES ('ST0568', 'Psychological wellbeing practitioner', 6, 'Health and science')
INSERT #Standard VALUES ('ST0571', 'Heritage engineering technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0572', 'Sales executive', 4, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0574', 'Ordnance munitions and explosives (OME) professional (integrated degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0575', 'School business professional', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0577', 'Ecologist (degree)', 7, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0580', 'Brewer', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0581', 'Textile technical specialist', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0582', 'Operating department practitioner', 6, 'Health and science')
INSERT #Standard VALUES ('ST0583', 'Mammography associate', 4, 'Health and science')
INSERT #Standard VALUES ('ST0584', 'Funeral director', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0585', 'Data scientist (integrated degree)', 6, 'Digital')
INSERT #Standard VALUES ('ST0586', 'Regulatory affairs specialist', 7, 'Health and science')
INSERT #Standard VALUES ('ST0587', 'Internal audit practitioner', 4, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0588', 'Propulsion technician', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0589', 'Production chef', 2, 'Catering and hospitality')
INSERT #Standard VALUES ('ST0590', 'Registrar (creative and cultural)', 6, 'Creative and design')
INSERT #Standard VALUES ('ST0592', 'Marina and boatyard operative', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0593', 'Community safety advisor', 3, 'Protective services')
INSERT #Standard VALUES ('ST0594', 'Funeral team member', 2, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0595', 'Air traffic controller', 5, 'Transport and logistics')
INSERT #Standard VALUES ('ST0596', 'Marketing executive', 4, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0597', 'Technician scientist', 5, 'Health and science')
INSERT #Standard VALUES ('ST0599', 'Dietitian', 6, 'Health and science')
INSERT #Standard VALUES ('ST0600', 'Hearing aid dispenser', 5, 'Health and science')
INSERT #Standard VALUES ('ST0601', 'Prosthetist and orthotist', 6, 'Health and science')
INSERT #Standard VALUES ('ST0602', 'Revenues and welfare benefits practitioner', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0603', 'Professional economist (integrated degree)', 6, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0604', 'Commercial laundry operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0605', 'Mineral products technician', 5, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0607', 'Metal fabricator', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0608', 'Accounts or finance assistant', 2, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0609', 'Clinical trials specialist (degree)', 6, 'Health and science')
INSERT #Standard VALUES ('ST0610', 'Internal audit professional', 7, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0611', 'Cultural heritage conservation technician', 4, 'Creative and design')
INSERT #Standard VALUES ('ST0612', 'Marketing manager', 6, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0613', 'Acoustics technician', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0614', 'Fall protection technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0615', 'Demolition operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0616', 'Wireless communications rigger', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0617', 'Facilities services operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0618', 'Speech and language therapist', 6, 'Health and science')
INSERT #Standard VALUES ('ST0619', 'Diagnostic radiographer', 6, 'Health and science')
INSERT #Standard VALUES ('ST0620', 'Therapeutic radiographer', 6, 'Health and science')
INSERT #Standard VALUES ('ST0621', 'Boatmaster', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0622', 'Bicycle mechanic', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0623', 'Marine technical superintendent (degree)', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0624', 'Food and drink engineer', 5, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0625', 'Creative digital design professional (integrated degree)', 6, 'Digital')
INSERT #Standard VALUES ('ST0626', 'Laboratory scientist (degree)', 6, 'Health and science')
INSERT #Standard VALUES ('ST0627', 'Ambulance support worker (emergency, urgent and non-urgent)', 3, 'Health and science')
INSERT #Standard VALUES ('ST0628', 'Cultural heritage conservator (degree)', 7, 'Creative and design')
INSERT #Standard VALUES ('ST0629', 'BEMS (building energy management systems) controls engineer', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0630', 'Beauty therapist', 2, 'Hair and beauty')
INSERT #Standard VALUES ('ST0631', 'Public health practitioner - integrated degree', 6, 'Health and science')
INSERT #Standard VALUES ('ST0632', 'Prosthetic and orthotic technician', 3, 'Health and science')
INSERT #Standard VALUES ('ST0633', 'Arts therapist', 7, 'Health and science')
INSERT #Standard VALUES ('ST0635', 'Nail services technician', 2, 'Hair and beauty')
INSERT #Standard VALUES ('ST0636', 'Beauty and make up consultant', 2, 'Hair and beauty')
INSERT #Standard VALUES ('ST0637', 'Packaging professional (integrated degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0639', 'Bespoke furniture maker', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0641', 'Tool process design engineer', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0644', 'Advertising and media executive', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0645', 'Train driver', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0647', 'Transport and warehouse operations supervisor', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0649', 'Bioinformatics scientist (degree)', 7, 'Health and science')
INSERT #Standard VALUES ('ST0651', 'Lightning protection operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0652', 'Building control surveyor (integrated degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0654', 'Fitted furniture design technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0655', 'Advanced furniture CNC technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0656', 'Advanced upholsterer', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0659', 'Materials process engineer (degree)', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0662', 'Automation and controls engineering technician', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0663', 'Employability practitioner', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0664', 'Library, information and archive services assistant', 3, 'Business and administration')
INSERT #Standard VALUES ('ST0666', 'Education technician (he assistant technician and simulation-based technician)', 3, 'Education and early years')
INSERT #Standard VALUES ('ST0668', 'Assistant buyer and assistant merchandiser', 6, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0669', 'Tramway construction operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0672', 'Electro-mechanical engineer', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0675', 'Materials science technologist (degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0682', 'Digital device repair technician', 3, 'Digital')
INSERT #Standard VALUES ('ST0683', 'Buying and merchandising assistant', 4, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0685', 'Wellbeing and holistic therapist', 3, 'Hair and beauty')
INSERT #Standard VALUES ('ST0693', 'Road surfacing operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0694', 'Career development professional', 6, 'Business and administration')
INSERT #Standard VALUES ('ST0695', 'Process leader', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0696', 'Post production technical operator', 4, 'Creative and design')
INSERT #Standard VALUES ('ST0697', 'Specialist community public health nurse', 7, 'Health and science')
INSERT #Standard VALUES ('ST0698', 'Transport planner (integrated degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0701', 'Orthodontic therapist (integrated)', 4, 'Health and science')
INSERT #Standard VALUES ('ST0708', 'Public sector compliance Investigator and officer', 3, 'Business and administration')
INSERT #Standard VALUES ('ST0709', 'District nurse', 7, 'Health and science')
INSERT #Standard VALUES ('ST0714', 'Environmental health practitioner (integrated degree)', 6, 'Health and science')
INSERT #Standard VALUES ('ST0736', 'Construction plant operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0740', 'Through life engineering services specialist (integrated degree)', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0741', 'Landscape technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0742', 'Chartered landscape professional', 7, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0743', 'Fenestration installer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0744', 'Fenestration fabricator', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0746', 'Fire safety inspector', 4, 'Protective services')
INSERT #Standard VALUES ('ST0747', 'Counter fraud investigator', 4, 'Protective services')
INSERT #Standard VALUES ('ST0748', 'Sustainability business specialist (integrated degree)', 7, 'Business and administration')
INSERT #Standard VALUES ('ST0749', 'Historic environment advice assistant', 4, 'Creative and design')
INSERT #Standard VALUES ('ST0750', 'Mastic asphalter', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0752', 'Drinks dispense technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0753', 'Express delivery sortation hub operative', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0757', 'Radio network technician', 3, 'Digital')
INSERT #Standard VALUES ('ST0759', 'Research scientist', 7, 'Health and science')
INSERT #Standard VALUES ('ST0761', 'Agriculture or horticulture professional adviser', 6, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0762', 'Information manager', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0763', 'Artificial intelligence (AI) data specialist', 7, 'Digital')
INSERT #Standard VALUES ('ST0764', 'Non home office police officer', 4, 'Protective services')
INSERT #Standard VALUES ('ST0765', 'Harbour master', 6, 'Transport and logistics')
INSERT #Standard VALUES ('ST0766', 'Debt adviser', 3, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0767', 'Water environment worker', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0769', 'Archaeological specialist (degree)', 7, 'Creative and design')
INSERT #Standard VALUES ('ST0770', 'Sports coach', 4, 'Health and science')
INSERT #Standard VALUES ('ST0772', 'Marine surveyor (degree)', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0774', 'Dispensing optician', 6, 'Health and science')
INSERT #Standard VALUES ('ST0778', 'Environmental practitioner (Degree)', 6, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0781', 'Registered nurse degree (NMC 2018)', 6, 'Health and science')
INSERT #Standard VALUES ('ST0782', 'Curator', 7, 'Creative and design')
INSERT #Standard VALUES ('ST0783', 'Costume technician - stage and screen', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0784', 'Nuclear reactor desk engineer', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0785', 'Human factors specialist', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0786', 'Associate continuing healthcare practitioner', 5, 'Health and science')
INSERT #Standard VALUES ('ST0787', 'Systems thinking practitioner', 7, 'Business and administration')
INSERT #Standard VALUES ('ST0788', 'Advanced forensic practitioner (custody or sexual offence)', 7, 'Health and science')
INSERT #Standard VALUES ('ST0789', 'Keeper and aquarist', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0790', 'Power and propulsion gas turbine engineer', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0791', 'Commercial catering equipment technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0792', 'Media production co-ordinator', 4, 'Creative and design')
INSERT #Standard VALUES ('ST0793', 'New furniture product developer', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0795', 'Data technician', 3, 'Digital')
INSERT #Standard VALUES ('ST0796', 'Senior professional economist (integrated degree)', 7, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0798', 'Clinical pharmacology scientist (integrated degree)', 7, 'Health and science')
INSERT #Standard VALUES ('ST0802', 'Curtain wall installer', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0805', 'Construction equipment maintenance mechanic', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0808', 'Marine electrician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0809', 'Coaching professional', 5, 'Business and administration')
INSERT #Standard VALUES ('ST0810', 'Procurement and supply assistant', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0811', 'Senior procurement and supply chain professional', 6, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0813', 'Senior people professional', 7, 'Business and administration')
INSERT #Standard VALUES ('ST0815', 'Trade union official', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0817', 'Compressed air and vacuum technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0820', 'Clinical associate in psychology (CAP) (integrated degree)', 7, 'Health and science')
INSERT #Standard VALUES ('ST0821', 'Thatcher', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0824', 'Signage technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0825', 'DevOps engineer', 4, 'Digital')
INSERT #Standard VALUES ('ST0827', 'Nursing associate (NMC 2018)', 5, 'Health and science')
INSERT #Standard VALUES ('ST0829', 'Health play specialist', 5, 'Health and science')
INSERT #Standard VALUES ('ST0830', 'Health and care intelligence specialist', 7, 'Health and science')
INSERT #Standard VALUES ('ST0831', 'Historic environment advisor', 7, 'Creative and design')
INSERT #Standard VALUES ('ST0832', 'Telecoms field operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0833', 'Ordnance munitions explosives technician', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0834', 'Ordnance munitions and explosives specialist (integrated degree)', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0841', 'Engineering manufacturing technician', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0842', 'Officer of the watch (near coastal)', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0843', 'Cleaning hygiene operative', 2, 'Health and science')
INSERT #Standard VALUES ('ST0845', 'Project controls professional', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0846', 'Garment maker', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0847', 'Engineer surveyor', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0851', 'Pipe welder', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0852', 'Plate welder', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0853', 'Quality practitioner', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0855', 'Space engineering technician', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0856', 'Space systems engineer', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0859', 'Fire safety engineer (degree)', 6, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0860', 'Infrastructure asset management professional', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0861', 'Asset manager', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0862', 'Domestic and sexual abuse support worker', 4, 'Care services')
INSERT #Standard VALUES ('ST0863', 'Digital accessibility specialist', 4, 'Digital')
INSERT #Standard VALUES ('ST0864', 'Senior culinary chef', 4, 'Catering and hospitality')
INSERT #Standard VALUES ('ST0865', 'Cyber security technician', 3, 'Digital')
INSERT #Standard VALUES ('ST0867', 'Playworker', 2, 'Care services')
INSERT #Standard VALUES ('ST0868', 'Early intervention practitioner', 4, 'Care services')
INSERT #Standard VALUES ('ST0869', 'Payroll assistant manager', 5, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST0872', 'Lifting equipment technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0873', 'Hygiene specialist', 4, 'Health and science')
INSERT #Standard VALUES ('ST0875', 'Small vessel chief engineer', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0876', 'Water process operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0877', 'Land referencer', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0878', 'Youth justice practitioner', 5, 'Protective services')
INSERT #Standard VALUES ('ST0881', 'Geotechnical engineer (integrated degree)', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0883', 'Market research executive', 4, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0884', 'Operational research specialist', 7, 'Business and administration')
INSERT #Standard VALUES ('ST0887', 'Fundraiser', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST0888', 'Early years practitioner', 2, 'Education and early years')
INSERT #Standard VALUES ('ST0889', 'Mortuary technician', 3, 'Health and science')
INSERT #Standard VALUES ('ST0890', 'Embalmer', 5, 'Health and science')
INSERT #Standard VALUES ('ST0892', 'Medical statistician', 7, 'Health and science')
INSERT #Standard VALUES ('ST0893', 'Clinical scientist', 7, 'Health and science')
INSERT #Standard VALUES ('ST0894', 'Service designer', 6, 'Business and administration')
INSERT #Standard VALUES ('ST0895', 'Enhanced clinical practitioner', 6, 'Health and science')
INSERT #Standard VALUES ('ST0896', 'Peer worker', 3, 'Health and science')
INSERT #Standard VALUES ('ST0898', 'Water network operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0899', 'Material cutter', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0900', 'Camera prep technician', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0901', 'VFX supervisor', 7, 'Creative and design')
INSERT #Standard VALUES ('ST0902', 'VFX artist or technical director', 6, 'Creative and design')
INSERT #Standard VALUES ('ST0904', 'Archivist and records manager', 7, 'Creative and design')
INSERT #Standard VALUES ('ST0905', 'Play therapist', 7, 'Care services')
INSERT #Standard VALUES ('ST0906', 'Youth support worker', 3, 'Care services')
INSERT #Standard VALUES ('ST0907', 'Aviation customer service operative', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0908', 'Aviation ground handler', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST0910', 'Knitted product manufacturing technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0912', 'Stained glass craftsperson', 4, 'Creative and design')
INSERT #Standard VALUES ('ST0915', 'Scenic automation technician', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0916', 'Scenic artist', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0917', 'Scenic construction technician', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0918', 'Hair, wigs, make-up and prosthetics technician', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0921', 'Arboriculturist', 4, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0922', 'Professional arboriculturist', 6, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0923', 'Professional forester (integrated degree)', 6, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0924', 'Horticulture and landscaping technical manager', 5, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0925', 'Junior advertising creative', 3, 'Creative and design')
INSERT #Standard VALUES ('ST0926', 'Countryside ranger', 4, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0929', 'Pastry chef', 3, 'Catering and hospitality')
INSERT #Standard VALUES ('ST0930', 'Anti-social behaviour and community safety officer', 4, 'Protective services')
INSERT #Standard VALUES ('ST0933', 'Post production engineer', 5, 'Creative and design')
INSERT #Standard VALUES ('ST0934', 'Corporate responsibility and sustainability practitioner', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0936', 'Town planning assistant', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0937', 'General farm worker', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0938', 'Livestock unit technician', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0940', 'Audiovisual technician', 5, 'Creative and design')
INSERT #Standard VALUES ('ST0943', 'Dog groomer', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0944', 'Assistant recording technician', 4, 'Creative and design')
INSERT #Standard VALUES ('ST0945', 'Outdoor learning specialist', 5, 'Health and science')
INSERT #Standard VALUES ('ST0946', 'Vet technician (livestock)', 5, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0948', 'Midwife (2019 NMC standards) (Integrated degree)', 6, 'Health and science')
INSERT #Standard VALUES ('ST0949', 'Applications support lead', 4, 'Digital')
INSERT #Standard VALUES ('ST0950', 'Healthcare engineering specialist technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0952', 'Fisher', 2, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST0953', 'Game programmer', 7, 'Digital')
INSERT #Standard VALUES ('ST0954', 'Aviation movement specialist', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST0957', 'Spatial data specialist', 7, 'Digital')
INSERT #Standard VALUES ('ST0958', 'Community health and wellbeing worker', 3, 'Health and science')
INSERT #Standard VALUES ('ST0960', 'Construction support technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0962', 'Print operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0963', 'Surface finisher', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST0964', 'Digital product manager', 4, 'Digital')
INSERT #Standard VALUES ('ST0966', 'Teacher for the sensory impaired', 7, 'Education and early years')
INSERT #Standard VALUES ('ST0967', 'Data protection and information governance practitioner', 4, 'Business and administration')
INSERT #Standard VALUES ('ST0973', 'Information communications technician', 3, 'Digital')
INSERT #Standard VALUES ('ST0974', 'Digital learning designer', 5, 'Digital')
INSERT #Standard VALUES ('ST0980', 'Fitted interiors installer', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0985', 'Lead traffic management operative', 2, 'Construction and the built environment')
INSERT #Standard VALUES ('ST0995', 'Doctor (Degree)', 7, 'Health and science')
INSERT #Standard VALUES ('ST0998', 'Trading standards professional', 6, 'Business and administration')
INSERT #Standard VALUES ('ST0999', 'Lead engineering maintenance technician', 4, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1007', 'Aviation flight operations coordinator', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST1016', 'Professional security operative', 2, 'Protective services')
INSERT #Standard VALUES ('ST1017', 'Domestic electrician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST1020', 'Low carbon heating technician', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST1021', 'Cyber security technologist (2021)', 4, 'Digital')
INSERT #Standard VALUES ('ST1025', 'Urban driver', 2, 'Transport and logistics')
INSERT #Standard VALUES ('ST1031', 'Multi-channel marketer', 3, 'Sales, marketing and procurement')
INSERT #Standard VALUES ('ST1105', 'Heritage construction specialist', 5, 'Construction and the built environment')
INSERT #Standard VALUES ('ST1273', 'Barbering professional', 2, 'Hair and beauty')
INSERT #Standard VALUES ('ST1291', 'Water industry treatment process technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1292', 'Water industry network technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1297', 'Creative industries production technician', 3, 'Creative and design')
INSERT #Standard VALUES ('ST1299', 'Cellular network field engineer', 4, 'Construction and the built environment')
INSERT #Standard VALUES ('ST1302', 'Governance officer', 4, 'Business and administration')
INSERT #Standard VALUES ('ST1303', 'Accounting finance manager', 6, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST1305', 'Machining technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1309', 'Mine management', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1311', 'Licensed conveyancer or licensed probate practitioner', 6, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST1312', 'Legal technician - conveyancing technician or probate technician', 4, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST1314', 'Biomedical scientist', 6, 'Health and science')
INSERT #Standard VALUES ('ST1315', 'Aircraft maintenance technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1317', 'Robotics engineer - degree', 6, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1318', 'Junior grip', 2, 'Creative and design')
INSERT #Standard VALUES ('ST1320', 'Assistant farm manager', 4, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST1321', 'Forest craftsperson', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST1322', 'Resilience and emergencies professional', 6, 'Protective services')
INSERT #Standard VALUES ('ST1323', 'Advanced sports turf technician', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST1324', 'Journalist', 5, 'Creative and design')
INSERT #Standard VALUES ('ST1325', 'Junior visual effects - VFX artist or assistant technical director - ATD', 4, 'Creative and design')
INSERT #Standard VALUES ('ST1327', 'Mobile transport refrigeration technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1328', 'Polymer processing technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1330', 'Power industry overhead linesperson', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1331', 'Power industry substation fitter', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1332', 'Power industry distribution cable jointer', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1334', 'Craft bricklayer', 3, 'Construction and the built environment')
INSERT #Standard VALUES ('ST1335', 'Senior florist', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST1338', 'Battery manufacturing technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1340', 'Advertising creative', 6, 'Creative and design')
INSERT #Standard VALUES ('ST1341', 'Social researcher', 6, 'Business and administration')
INSERT #Standard VALUES ('ST1343', 'Digital forensic technician', 4, 'Digital')
INSERT #Standard VALUES ('ST1348', 'Drainage network operative', 2, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1349', 'Lead baker', 3, 'Catering and hospitality')
INSERT #Standard VALUES ('ST1356', 'Geoscientist (integrated degree)', 6, 'Health and science')
INSERT #Standard VALUES ('ST1359', 'Animal care and welfare manager', 3, 'Agriculture, environmental and animal care')
INSERT #Standard VALUES ('ST1362', 'Soil scientist', 7, 'Health and science')
INSERT #Standard VALUES ('ST1368', 'Chartered legal executive litigator and advocate', 7, 'Legal, finance and accounting')
INSERT #Standard VALUES ('ST1377', 'Optical assistant 2022', 3, 'Health and science')
INSERT #Standard VALUES ('ST1378', 'Rail infrastructure operator 2022', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST1379', 'Learning and skills mentor', 4, 'Education and early years')
INSERT #Standard VALUES ('ST1380', 'Learning and skills assessor', 3, 'Education and early years')
INSERT #Standard VALUES ('ST1381', 'Advanced robotics engineer', 7, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1386', 'Data engineer', 5, 'Digital')
INSERT #Standard VALUES ('ST1388', 'Photographer', 4, 'Creative and design')
INSERT #Standard VALUES ('ST1406', 'Science manufacturing technician 2023', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1407', 'Process industry manufacturing technician', 3, 'Engineering and manufacturing')
INSERT #Standard VALUES ('ST1418', 'Specialist community public health nurse (NMC 2022)', 7, 'Health and science')
INSERT #Standard VALUES ('ST1419', 'Community nurse specialist practitioner (NMC 2022)', 7, 'Health and science')
INSERT #Standard VALUES ('ST1438', 'Transport scheduler', 3, 'Transport and logistics')
INSERT #Standard VALUES ('ST1442', 'Publishing professional', 4, 'Creative and design')

MERGE [Standard] [Target] USING #Standard [Source]
ON ([Source].[StandardReference] = [Target].[StandardReference])
WHEN MATCHED
    THEN UPDATE SET 
        [Target].[StandardTitle] = [Source].[StandardTitle],
        [Target].[StandardLevel] = [Source].[StandardLevel],
        [Target].[StandardSector] = [Source].[StandardSector]

WHEN NOT MATCHED BY TARGET 
    THEN INSERT ([StandardReference], [StandardTitle], [StandardLevel], [StandardSector] )
         VALUES ([Source].[StandardReference], [Source].[StandardTitle], [Source].[StandardLevel], [Source].[StandardSector]);
COMMIT TRANSACTION
