CREATE TABLE [dbo].[ProviderResponse]
(
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [ContactName] NVARCHAR(256) NOT NULL CONSTRAINT [DF_ProviderResponse_ContactName] DEFAULT '',
    [Email] VARCHAR(256) NOT NULL,
    [PhoneNumber] VARCHAR(25) NOT NULL,
    [Website] VARCHAR(256) NOT NULL,
    [RespondedAt] DATETIME2 NOT NULL,
    [RespondedBy] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_ProviderResponse_RespondedBy] DEFAULT '00000000-0000-0000-0000-000000000000',
    [ValidFrom] DATETIME2 (0) GENERATED ALWAYS AS ROW START,
    [ValidTo] DATETIME2 (0) GENERATED ALWAYS AS ROW END,
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[ProviderResponseHistory]));
GO
